### ISSUE TITLE
Any luck on finishing this?

### ISSUE THREAD

**Issue by Fresheyeball** [tazjin/hs-google-adminsdk#1]
I have to work with the google admin sdk right now, and so might be willing to contribute to this project. Please let me know your thoughts on current status, and where this project ended.

**Comment by tazjin** [comment]
Hey,

I don't work with the project that I needed this for anymore, so I currently don't plan to work more on this. Other than implementing the types for some of the API objects nothing has really happened in this project, but you might be able to take those types and a library like `http-conduit` and quickly mash something up that can speak to Google's API.

Feel free to fork and take over the project, if you want I can add an according license.

//V

**Comment by Fresheyeball** [comment]
If you add MIT license I am likely to use this code atleast.

**Comment by Fresheyeball** [comment]
Thanks!
